### ISSUE TITLE
Attachments can't be downloaded on TDesktop

### ISSUE THREAD

**Issue by p1ratrulezzz** [makkarpov/mtoxy#2]
### Server:
OS Ubuntu 18.04
Network: epoll

### Client
OS  Ubuntu 14.04
TDesktop: 1.2.24

### Expected reaction
Attachments are downloaded

### Actual reaction
I can upload any attachments, I can't download photo attachments (forever loading icon)

No errors on server side in logs, tried also with network transport = nio, all the same.

Android clients work fine.

**Comment by makkarpov** [comment]
There are two types of Telegram attachments, e.g. for photos: they can be photos uploaded to Telegram servers directly and they can be photos that are created as previews for URLs. Previews don't work for me either, while directly uploaded works fine.

I don't know why they don't work, since as you mentioned there are no dropped/stalled connections on the proxy. I'll investigate it, but this is not a high-priority issue (for previews).

Can you confirm that the issue occurs with directly uploaded attachments?

**Comment by p1ratrulezzz** [comment]
Hello. Yes, with all attachments, but only on desktop client. Upload is OK, download: not ok

Test case:
1. Uploading a file using Telegram on Android
2. Trying to download using Desktop

**Comment by alexbers** [comment]
Hi,
I was also meet this bug when I was developing mtproto proxy https://github.com/alexbers/mtprotoproxy.

To fix it, please, use this formula to get datacenter index:
dc_idx = abs(int.from_bytes(decrypted[60:62], "little", signed=True)) - 1

The key point is that you should do abs, because the client sends negative numbers when tries to download attachements.

Best,
Alexander Bersenev

**Comment by makkarpov** [comment]
Thank you very much. I had fixed it in 3a1a9637fb29e7f31cb6a0b6c4d755dd9e2309b3 (release 0.3)

**Comment by p1ratrulezzz** [comment]
Great! Its working, I confirm. thanks
